In [2]:
import numpy as np
myShort = np.short (15)

In [3]:
print (myShort)

15


In [4]:
myVect = np.array([1, 2, 3, 4])
for Value1 in myVect:
    print(Value1)

1
2
3
4


In [6]:
myVect = np.arange(1, 10, 2)
for Value1 in myVect:
    print(Value1)

1
3
5
7
9


In [7]:
myVect2 = np.array (np.int16([1, 2, 3, 4]))
for Value2 in myVect2:
    print(Value2)

1
2
3
4


In [9]:
myVect2 = myVect2 + 1
for Value2 in myVect2:
    print(Value2)

2
3
4
5


In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([2, 2, 4, 4])

a == b

array([False,  True, False,  True])

In [13]:
a = np.array([True, False, True, False])
b = np.array([True, True, False, False])

np.logical_and(a,b)

array([ True, False, False, False])

In [14]:
np.logical_not(a)

array([False,  True, False,  True])

In [15]:
np.logical_xor(a, b)

array([False,  True,  True, False])

In [3]:
Vector = np.array([1, 2, 3, 4])
Vector * Vector

array([ 1,  4,  9, 16])

In [4]:
np.multiply(Vector, Vector)

array([ 1,  4,  9, 16])

In [5]:
Vector.dot(Vector)

30