In [1]:
import numpy as np

In [4]:
myMatrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(myMatrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
myMatrix[1, 2]

6

In [8]:
myMatriz = np.array([[[1, 2], 
                      [3,4]],
                    [[5, 6], 
                    [7, 8]]], dtype=int32)
print(myMatriz)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [10]:
myMatriz[0, 1, 1]

4

In [13]:
myMatrix2 = np.ones([4, 4], dtype=np.bool_)
print(myMatrix2)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [15]:
Matrix = np.mat([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print(Matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
myMatrix = np.asmatrix(myMatrix)
print(type(myMatrix))

<class 'numpy.matrix'>


In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = a * a
print(b)

[[ 1  4  9]
 [16 25 36]]


In [24]:
c = np.array([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
a.dot(c)

array([[22, 28, 34],
       [49, 64, 79]])

In [30]:
a = np.asmatrix(a)
d = np.matrix([[1, 2, 3], [3, 4, 5], [5, 6, 7]])
x = a * d
print(str(x))

[[22 28 34]
 [49 64 79]]


In [31]:
ChangeIt = np.array([1, 2, 3, 4, 5, 6, 7, 8])
ChangeIt

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
ChangeIt.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [42]:
ChangeIt = ChangeIt.reshape(2, 4)
ChangeIt

array([[1, 5, 3, 7],
       [2, 6, 4, 8]])

In [43]:
ChangeIt = np.transpose(ChangeIt)
ChangeIt

array([[1, 2],
       [5, 6],
       [3, 4],
       [7, 8]])

In [44]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [46]:
a = np.array([[1, 2], [3, 4]])
b = np.linalg.inv(a)
print(b)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [50]:
np.allclose(np.dot(a, b), np.identity(2))

True